# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('friends', models.ManyToManyField(related_name='_person_friends_+', to='friends.Person')),
                ('suggestion', models.ManyToManyField(related_name='_person_suggestion_+', to='friends.Person')),
            ],
        ),
    ]
